package organotiki.mobile.NorthnetStatistics.objects;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class GlobalVar extends RealmObject {

    @PrimaryKey
    private String ID;
    private String LocalIP;
    private String OnlineIP;
    private User myUser;
    private String LastUpdate;
    private String VerNum;

    // Standard getters & setters generated by your IDE…

    public GlobalVar() {
    }

    public GlobalVar(String ID, String localIP, String onlineIP) {
        this.ID = ID;
        LocalIP = localIP;
        OnlineIP = onlineIP;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getLocalIP() {
        return LocalIP;
    }

    public void setLocalIP(String localIP) {
        LocalIP = localIP;
    }

    public String getOnlineIP() {
        return OnlineIP;
    }

    public void setOnlineIP(String onlineIP) {
        OnlineIP = onlineIP;
    }

    public User getMyUser() {
        return myUser;
    }

    public void setMyUser(User myUser) {
        this.myUser = myUser;
    }


    public String getLastUpdate() {
        return LastUpdate;
    }

    public void setLastUpdate(String lastUpdate) {
        LastUpdate = lastUpdate;
    }

    public String getVerNum() {
        return VerNum;
    }

    public void setVerNum(String verNum) {
        VerNum = verNum;
    }
}
