package organotiki.mobile.NorthnetStatistics.objects;

import java.math.RoundingMode;
import java.text.DecimalFormat;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class Item extends RealmObject {

    @PrimaryKey
    private String ID;
    private Double ABRatio=0.0;
    private Boolean HasSpecialUnit=false;
    private Double SpecialUnitRatio=0.0;
    private String Code;
    private String Description;
    private String PageValue;
    private Double Price= 0.0;
    private Double CostPrice = 0.0;
    private String String0;
    private String String1;
    private Double DiscountA=0.0;
    private String ItemSalesRemark;
    private Boolean Active;
    private Boolean BlockPurchase;
    private Boolean BlockSales;
    private Boolean Deleted;
    private String imagePath;
    private String CPVCODE;
    private String SALESAADECLASSCODE;
    private String PURCHASEAADECLASSCODE;
    private String AADECLASSIFICATIONTYPESCODE;
    private String AADECLASSIFICATIONVATCODE;
    private boolean isLotTracking;

// Standard getters & setters generated by your IDE…

    public Item() {
    }

    public String getCPVCODE() {
        return CPVCODE;
    }

    public void setCPVCODE(String CPVCODE) {
        this.CPVCODE = CPVCODE;
    }

    public String getSALESAADECLASSCODE() {
        return SALESAADECLASSCODE;
    }

    public void setSALESAADECLASSCODE(String SALESAADECLASSCODE) {
        this.SALESAADECLASSCODE = SALESAADECLASSCODE;
    }

    public String getAADECLASSIFICATIONTYPESCODE() {
        return AADECLASSIFICATIONTYPESCODE;
    }

    public void setAADECLASSIFICATIONTYPESCODE(String AADECLASSIFICATIONTYPESCODE) {
        this.AADECLASSIFICATIONTYPESCODE = AADECLASSIFICATIONTYPESCODE;
    }

    public String getAADECLASSIFICATIONVATCODE() {
        return AADECLASSIFICATIONVATCODE;
    }

    public void setAADECLASSIFICATIONVATCODE(String AADECLASSIFICATIONVATCODE) {
        this.AADECLASSIFICATIONVATCODE = AADECLASSIFICATIONVATCODE;
    }

    public String getPURCHASEAADECLASSCODE() {
        return PURCHASEAADECLASSCODE;
    }

    public void setPURCHASEAADECLASSCODE(String PURCHASEAADECLASSCODE) {
        this.PURCHASEAADECLASSCODE = PURCHASEAADECLASSCODE;
    }

    public boolean isLotTracking() {
        return isLotTracking;
    }

    public void setLotTracking(boolean lotTracking) {
        isLotTracking = lotTracking;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getString0() {
        return String0;
    }

    public void setString0(String string0) {
        String0 = string0;
    }

    public String getString1() {
        return String1;
    }

    public void setString1(String string1) {
        String1 = string1;
    }

    public Boolean getBlockPurchase() {
        return BlockPurchase;
    }

    public void setBlockPurchase(Boolean blockPurchase) {
        BlockSales = blockPurchase;
    }

    public Boolean getBlockSales() {
        return BlockSales;
    }

    public void setBlockSales(Boolean blockSales) {
        BlockSales = blockSales;
    }

    public Boolean getActive() {
        return Active;
    }

    public void setActive(Boolean active) {
        Active = active;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getCode() {
        return Code;
    }

    public void setCode(String code) {
        Code = code;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String decription) {
        Description = decription;
    }

    public Double getPrice() {
        return Price;
    }

    public void setPrice(Double price) {
        Price = price;
    }

    public String getItemSalesRemark() {
        return ItemSalesRemark;
    }

    public void setItemSalesRemark(String itemSalesRemark) {
        this.ItemSalesRemark = itemSalesRemark;
    }

    public Double getABRatio() {
        return ABRatio;
    }

    public void setABRatio(Double ABRatio) {
        this.ABRatio = ABRatio;
    }

    public Boolean getHasSpecialUnit() {
        return HasSpecialUnit;
    }

    public void setHasSpecialUnit(Boolean hasSpecialUnit) {
        HasSpecialUnit = hasSpecialUnit;
    }

    public Double getSpecialUnitRatio() {
        return SpecialUnitRatio;
    }

    public void setSpecialUnitRatio(Double specialUnitRatio) {
        SpecialUnitRatio = specialUnitRatio;
    }

    public Double getCostPrice() {
        return CostPrice;
    }

    public void setCostPrice(Double costPrice) {
        this.CostPrice = costPrice;
    }

    public String getPageValue() {
        return PageValue;
    }

    public void setPageValue(String pageValue) {
        PageValue = pageValue;
    }

    public Double getDiscountA() {
        return DiscountA;
    }

    public void setDiscountA(Double discountA) {
        DiscountA = discountA;
    }

    public Boolean getDeleted() {
        return Deleted;
    }

    public void setDeleted(Boolean deleted) {
        Deleted = deleted;
    }

    public String getDiscountAText() {

        DecimalFormat decim = new DecimalFormat("0.00");
        decim.setRoundingMode(RoundingMode.HALF_UP);
        return decim.format(DiscountA).replace(",", ".");
    }

    public void setDiscountAText(String discountA) {
        DiscountA = Double.parseDouble(discountA.replace(",", ".").equals("") ? "0" : discountA.replace(",", "."));
    }
}