package organotiki.mobile.NorthnetStatistics.objects;

import java.util.List;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class User extends RealmObject {

    @PrimaryKey
    private String ID;
    private String Username;
    private String Password;
    private String FullName;
    private String Email;
    private Boolean isAdmin;
    // Standard getters & setters generated by your IDE…


    public User() {
    }

    public User(String ID, String username, String password, String fullName,String email,Boolean isAdmin) {
        this.ID = ID;
        Username = username;
        Password = password;
        FullName = fullName;
        Email=email;
        this.isAdmin=isAdmin;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getUsername() {
        return Username;
    }

    public void setUsername(String username) {
        Username = username;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String password) {
        Password = password;
    }

    public String getFullName() {
        return FullName;
    }

    public void setFullName(String fullName) {
        FullName = fullName;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String email) {
        Email = email;
    }

    public Boolean getAdmin() {
        return isAdmin;
    }

    public void setAdmin(Boolean admin) {
        isAdmin = admin;
    }
}
